fields:
  site:
    name: Joby's Site

# Should be disabled in favor of actual cron jobs if possible
cron:
  route_enabled: false
  poor_mans_cron: false

# disable guest signin
usermenu:
  guest_signin: false

# Generally should be fine for most sites
theme:
  timezone: America/Denver
  bundle_css: true
  bundle_js: true
  head_cache_ttl: -1
  active_themes: [hub]
themes:
  hub:
    variables:
      light:
        background: "#ffffff"
        background-dark: "#f6f8fa"
        background-darker: "#e8eaed"
        background-light: "#f5f6fe"
        background-lighter: "#e8f3ff"
        background-bright: "#deeeff"
        color: "#16192f"
        line-length: 45em
        border-radius: 4px
        border: 1px
        shadow: calc(var(--grid)/8) calc(var(--grid)/4) var(--grid) rgba(22, 25, 47, 0.25)
        shadow-inset: inset calc(var(--grid)/8) calc(var(--grid)/4) var(--grid) rgba(22, 25, 47, 0.25)
        font:
          content: '"Open Sans", sans-serif'
          header: '"Open Sans", sans-serif'
          ui: '"Open Sans", sans-serif'
          code: '"Hack", monospace'
        cue:
          interactive: "#2188ff"
          information: "#0096d7"
          safe: "#28a745"
          warning: "#ddb100"
          danger: "#e51400"
        theme:
          neutral: "#6a737d"
          accent: "#5a96da"
          highlight: "#f9826c"
        link:
          normal: "#0969da"
          visited: "#5876bf"
          focus: "#0969da"
          active: "#0969da"
      dark:
        background: "#24292e"
        color: "#c9dee8"
        shadow: calc(var(--grid)/8) calc(var(--grid)/4) var(--grid) rgba(31, 36, 40, 0.75)
        shadow-inset: inset calc(var(--grid)/8) calc(var(--grid)/4) var(--grid) rgba(31, 36, 40, 0.75)
        link:
          normal: "#0a6aff"
          visited: "#698de5"
          focus: "#0a6aff"
          active: "#0a6aff"

errors:
  display_trace: false

cache:
  ttl: 300
  template_ttl: -1
  content_ttl: 300

files:
  ttl: -1
  css:
    minify: true
    sourcemap: false
    keepimportantcomments: true

user_sources:
  cas:
    providers:
      dev:
        active: false
        name: Dev login provider
        mock_cas_user: true