debug: false
config:
    timezone: 'America/Denver'
    errorHandler: '\CoreBundle\ErrorHandler'
    fields:
        siteName: by Joby
        pageTitle: no title
        pageBody: no content
        libraries: false
    content:
        path: '../content'
        ttl: 5
        static:
            jpg:
                mime: image/jpeg
                ttl: 3600
            jpeg:
                mime: image/jpeg
                ttl: 3600
            png:
                mime: image/png
                ttl: 3600
            gif:
                mime: image/gif
                ttl: 3600
            css:
                mime: text/css
                ttl: 3600
            js:
                mime: application/javascript
                ttl: 3600
    twig:
        path: '../templates'
    monolog:
        logfile: 'logs/monolog.log'
        level: 'WARNING'