site:
  # Site address must be properly specified here, or you'll get 404 errors
  # Needs to have a trailing slash, and include the http/https://
  url: 'https://www.byjoby.com/'
  content_dir  : '${directories.base}/content'

addons:
  activate:
    - php-content
    - static-pages
    - syntax-highlighting
    - taxonomy
  config:
    leafcutter/addon-taxonomy:
      taxonomies:
        projects:
          displayName: Projects
          public: true
          termsPerPage: 10
          pagesPerPage: 10
          patterns:
            explicit:
              pattern: '@project\{(?P<name>[^\}]+)\}'
              keep: false

templates:
  site:
    # Site name to display in header/title
    name: Ye' Olde Site By Joby
