name: Deploy to staging
on:
  push:
    branches-ignore: [production]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      # Basic checkout and composer setup
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          version: latest
          php_version: 8.1
          args: --no-dev --ignore-platform-reqs --optimize-autoloader --apcu-autoloader

      # Shut down site and prepare environment
      # Clear all cache and asset files, for staging we don't care about continuity
      - name: Enter maintenance mode, prep environment
        uses: appleboy/ssh-action@master
        with:
          host: staging.byjoby.com
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            touch /home/${{ secrets.DEPLOY_USER }}/staging.byjoby.com/.maintenance
            rm -rf /home/${{ secrets.DEPLOY_USER }}/staging.byjoby.com/cache/*
            rm -rf /home/${{ secrets.DEPLOY_USER }}/static-staging.byjoby.com/byjoby.com/*

      # Do actual SSH deploy process, syncing changed/deleted files with server
      # doesn't sync some git/dev stuff, or env config
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: -crlpEtzi --delete
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: staging.byjoby.com
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          TARGET: /home/${{ secrets.DEPLOY_USER }}/staging.byjoby.com
          EXCLUDE: /.maintenance, /.htaccess, /env.yaml, /.git/, /.github/, /storage/, /cache/, /dev/, /web/index-dev.php

      # copy production database and storage directory
      - name: Copy production database and storage
        uses: appleboy/ssh-action@master
        with:
          host: staging.byjoby.com
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            cd /home/${{ secrets.DEPLOY_USER }}/staging.byjoby.com
            /usr/local/php81/bin/php scripts/copy-production.php
            rsync -crlpEtzi --delete /home/${{ secrets.DEPLOY_USER }}/byjoby.com/storage/ /home/${{ secrets.DEPLOY_USER }}/staging.byjoby.com/storage

      # Run database migrations
      - name: Database migrations
        uses: appleboy/ssh-action@master
        with:
          host: staging.byjoby.com
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            cd /home/${{ secrets.DEPLOY_USER }}/staging.byjoby.com
            /usr/local/php81/bin/php vendor/bin/phinx migrate

      # Remove .maintenance file to reactivate site
      - name: Leave maintenance mode
        uses: appleboy/ssh-action@master
        with:
          host: staging.byjoby.com
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: rm /home/${{ secrets.DEPLOY_USER }}/staging.byjoby.com/.maintenance
